'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
'''
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        cache = {}
        for i in range(len(s)):
            cache[s[i]] = cache[s[i]] + 1 if s[i] in cache else 1
            cache[t[i]] = cache[t[i]] - 1 if t[i] in cache else -1
        cache[t[-1]] = cache[t[-1]] - 1 if t[-1] in cache else -1
        for key in cache.keys():
            if cache[key] == -1:
                return key